BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "EventStore" (
	"Id"	INTEGER NOT NULL UNIQUE,
	"Key"	TEXT NOT NULL,
	"AssemblyQualifiedName"	TEXT NOT NULL,
	"Value"	TEXT NOT NULL,
	"Version"	INTEGER,
	PRIMARY KEY("Id" AUTOINCREMENT)
);
COMMIT;
